Testing To Do list: part 2
Danny-imo/To-do-list pull request #8
Opened 2023-07-28 15:05 UTC by Danny-imo

## In This PR
**I, @Danny-imo  and @Kaiserabbas  implemented the following:**

- Used jest framework for testing.
- Created a test file(s) (`[..].test.js`) for a file(s) containing the following functions:
    - a function for editing the task description.
    - a function for updating an item's 'completed' status.
    - the "Clear all completed" function.
- Used the mock storage object you have created in Part 1 of this project to mock the *localStorage* updates.
- Mocked the HTML elements to test DOM manipulation functions.
- Made sure we grouped our tests using the `describe()` method.

2023-07-28 15:18 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @Danny-imo, @Kaiserabbas :wave:

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Mandatory Changes ♻️

- [ ] It would be nice if you include Webhint in the linters setup because you guys have not included Webhint in the linters setup

2023-07-28 16:05 UTC, Kaiserabbas commented
Webhint has been included in the CI/CD workflow. Kindly process the review.

2023-07-28 16:28 UTC, shahadat3669 requested changes
Hi @Danny-imo, @Kaiserabbas , 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Descriptive PR Title
✅ Descriptive PR Description


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 16:28 UTC, shahadat3669 commented on src/tests/task.test.js
> +  });
- [ ] 👋 Thank you for successfully passing the tests. However, there appears to be an issue with the `clearCompletedTasks` functionality. Upon careful inspection of the `initialTasks` list, I noticed that there are two tasks with a `completed` value of `true`, and one task with a `completed` value of `false`. As per the project requirements, the `clearCompletedTasks` function should delete all tasks from the `tasks` array whose `completed` value is `true`. However, the current implementation is removing all tasks, regardless of their `completed` status. Please adjust your test cases,  so that the `clearCompletedTasks` function is properly evaluated in the test cases as per the project requirements. Keep up the excellent work, and happy coding! 💻🌟🚀

2023-07-28 16:28 UTC, shahadat3669 commented on src/tests/task.test.js
> +  });
- [ ] 👋 Thank you for your test submission. Based on the test description, it appears to be intended for updating existing task descriptions. However, I noticed that the `editTask()` function, which is responsible for editing tasks, is not being called in the test case. To ensure that the test accurately evaluates the functionality of updating tasks, please make sure to call the `editTask()` function with appropriate parameters that reflect the changes made to the task description. This will help ensure that the function is being properly tested and that the task descriptions are being updated as intended. Keep up the good work, and happy coding! 💻🌟🚀

2023-07-28 16:28 UTC, shahadat3669 commented on src/tests/task.test.js
> +    });
- [ ] Thank you for your test submission. After carefully reviewing the test case, it appears that it is not accurately testing the function responsible for toggling the `completed` value of a specific task. To ensure that the test evaluates the function correctly, please consider the following adjustments:

  1. Ensure that you are calling the correct function that handles the toggling of the `completed` value for a specific task. Double-check the function name and make any necessary updates.
  
  2. Provide appropriate test data and parameters to the function to simulate the toggling of the `completed` value for a specific task. This will help verify that the function behaves as expected and update the `completed` status accordingly.
  
  3. Include specific assertions in the test case to verify that the `completed` value of the task is toggled correctly. Use test assertions or methods to check if the `completed` value is changed as intended.

By making these adjustments, your test case will accurately evaluate the functionality of the function responsible for toggling the `completed` value of tasks and ensure that the function is working properly. Keep up the good work, and happy coding! 💻🌟🚀

2023-07-29 15:52 UTC, AbayomiOlaoye approved these changes
## STATUS: APPROVED :green_circle:  

Hi @Team  :wave: :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Cleanly written code :white_check_mark: 
- App runs well and functions as expected ✅ 
- Unit tests were implemented as suggested :heavy_check_mark: 
- Nicely implemented UI styles ✅ 
- Great teamwork ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 15:58 UTC, merged